### ISSUE TITLE
Feil i gjengivelse av matte i TTS-bok?

### ISSUE THREAD

**Issue by ThomasGTsigaridas** [nlbdev/service-stem#45]
@GauteR

Her funker ikke matteskriptet helt bra eller? Det skal vel stå "...4 multiplied by 10 to the power of 4 equation end", ikke "...4 multiplied by to the power of 10 to the power of 4 equation end km."? Fra 284286:

![matherror](https://user-images.githubusercontent.com/51702751/198532363-1341b733-e8f2-4ec0-b325-e81111daf932.PNG)

**Comment by GauteR** [comment]
Som sagt tidligere, tenker jeg at det har noe med oppmerking å gjøre. Hvor det er kodet som følgende: `<math>...</math>km` og heller burde vært `<math>...<mtext>km</mtext></math>` - tenker dette er en India sak. Men kan notere det til oppdatering av retningslinjer.
