### ISSUE TITLE
Update documentation to clarify base structure with the display attribute

### ISSUE THREAD

**Issue by GauteR** [nlbdev/service-stem#9]
- if the parent is `<div>` or `<section>`, the display attribute should be `block`
- if the parent is `<p>`, the display attribute should be `inline`
- `display:inline` must never stand alone within a `<p>`: if this occurs, the `<p>` should be removed and the math element should be a `display:block`

**Comment by GauteR** [comment]
```python
if math/@display is missing:
    if sibling non-empty text => inline
    elif sibling element 'a', 'abbr', 'bdo', 'br', 'code', 'dfn', 'em', 'img',
                         'kbd', 'q', 'samp', 'span', 'strong', 'sub', 'sup' => inline
    elif parent p => inline
    else => block
```

**Comment by josteinaj** [comment]
Hva med noe sånt som dette:

The `display` attribute must be included and used correctly on the `math` element.

From the MathML 3 specification:

> specifies whether the enclosed MathML expression should be rendered as a separate vertical block (in display style) or inline, aligned with adjacent text.

https://www.w3.org/TR/MathML3/chapter2.html#interf.toplevel

From the description on mozilla.org:

> This enumerated attribute specifies how the enclosed MathML markup should be rendered. It can have one of the following values:
> 
> - block, which means that this element will be displayed outside the current span of text, as a block that can be positioned anywhere without changing the meaning of the text;
> - inline, which means that this element will be displayed inside the current span of text, and cannot be moved out of it without changing the meaning of that text.

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/math#attr-display

It should be possible to implement this in practice using the following rules:

- If the `<math>` element has a sibling node which is either a non-empty text node, or one of the following inline elements, then the `display` attribute should be set to `"inline"`: `<a>`, `<abbr>`, `<bdo>`, `<br>`, `<code>`, `<dfn>`, `<em>`, `<img>`, `<kbd>`, `<q>`, `<samp>`, `<span>`, `<strong>`, `<sub>`, `<sup>`.

- The `<math>` element must not be the only node in an inline context. So for instance, while `<p><math display="inline">…</math></p>` is technically valid, it should rather be written as `<math display="block">…</math>`. But if there are non-empty text nodes or inline elements in the same context, then `display="inline"` should still be used: `<p>text text <math display="inline">…</math> <span>more text</span></p>` is correct.

- `<math>` elements that are not in an inline context, should use `display="block"`.

See also: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements

**Comment by josteinaj** [comment]
I tillegg:

> If the `<math>` element has a **sibling or parent node** (…)

…sånn at parent også sjekkes. Og en spesiell regel for noen flow-elementer:

> If the `<math>` element does not have any sibling elements or non-empty text nodes, and the parent element is either `<figcaption>`, `<dd>`, `<li>`, `<caption>`, `<th>` or `<td>`, then the `display` attribute should be "inline".

…og da starte det neste punktet med:

> **Except for the previous case, the** `<math>` element must not be the only node in an inline context. (…)

@espso @GauteR

**Comment by josteinaj** [comment]
Altså, oppdatert:

1. If the `<math>` element has a sibling or parent node node which is either a non-empty text node (note that text nodes consisting only of whitespace are considered "empty"), or one of the following inline elements, then the `display` attribute should be set to "inline": `<a>`, `<abbr>`, `<bdo>`, `<br>`, `<code>`, `<dfn>`, `<em>`, `<img>`, `<kbd>`, `<q>`, `<samp>`, `<span>`, `<strong>`, `<sub>`, `<sup>`.

2. If the `<math>` element does not have any sibling elements or non-empty text nodes, and the parent element is either `<figcaption>`, `<dd>`, `<li>`, `<caption>`, `<th>` or `<td>`, then the `display` attribute should be "inline".

3. Except for the previous case, the `<math>` element must not be the only node in an inline context. So for instance, while
  ```html
  <p>
    <math display="inline">…</math>
  </p>
  ```
  is technically valid, it should rather be written as
  ```html
  <math display="block">…</math>
  ```
  But if there are non-empty text nodes or inline elements in the same context (i.e. siblings or parent), then `display="inline"` should still be used. For instance, this is correct:
  ```html
  <p>
     text text
     <math display="inline">…</math>
     <span>more text</span>
  </p>
  ```

4. `<math>` elements that are not in an inline context according to the rules above, should use `display="block"`.
